version: '3.8'

services:
  mongo:
    image: mongo:7.0
    hostname: mongo
    restart: unless-stopped
    command: >
      mongod --replSet rs0 --bind_ip_all --wiredTigerCacheSizeGB 0.25
    volumes:
      - mongo_data:/data/db
    networks:
      - rinha-network
    healthcheck:
      test: |
        mongosh --host mongo:27017 --quiet --eval "
          try {
            const status = rs.status();
            if (status.myState === 1 || status.myState === 2) quit(0);
            else quit(1);
          } catch (e) {
            rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'mongo:27017' }] });
            quit(1);
          }"
      interval: 8s
      timeout: 5s
      retries: 15
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "260M"

  mongo-setup:
    image: mongo:7.0
    # Não nomeamos container para evitar conflitos em reruns
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./setup-mongo.sh:/setup-mongo.sh:ro
    networks:
      - rinha-network
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - DB_NAME=rinhaDB
      - SKIP_DROP=false
    entrypoint: ["bash", "/setup-mongo.sh"]
    restart: "no"

  api01:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    depends_on:
      mongo-setup:
        condition: service_completed_successfully
    environment:
      - MONGODB_URI=mongodb://mongo:27017/rinhaDB?replicaSet=rs0&retryWrites=true&w=majority
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-1
      - APP_RUN_MODE=hybrid
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "70M"
    healthcheck:
      # roda INSIDE do container (por isso o runtime contém curl)
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 45s

  api02:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api02
    depends_on:
      mongo-setup:
        condition: service_completed_successfully
    environment:
      - MONGODB_URI=mongodb://mongo:27017/rinhaDB?replicaSet=rs0&retryWrites=true&w=majority
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-2
      - APP_RUN_MODE=api
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "70M"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 45s

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api01:
        condition: service_healthy
      api02:
        condition: service_healthy
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10M"

volumes:
  mongo_data:

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true
    name: payment-processor
