services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    # ✅ A MUDANÇA CRÍTICA ESTÁ AQUI:
    # Limitamos o cache interno do MongoDB para 100MB.
    command: >
      mongod --replSet rs0 --bind_ip_all --wiredTigerCacheSizeGB 0.1
    volumes:
      - mongo_data:/data/db
    networks:
      - rinha-network
    healthcheck:
      test: |
        mongosh --host mongo:27017 --quiet --eval "
          try {
            const status = rs.status();
            if (status.myState === 1 || status.myState === 2) quit(0);
            else quit(1);
          } catch (e) {
            rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'mongo:27017' }] });
            quit(1);
          }"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          # ✅ MEMÓRIA REDUZIDA: Agora o contêiner tem um limite seguro.
          memory: "150M"

  redis:
    image: redis:7.2-alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory 40mb # <-- Reduzido, pois Redis é muito eficiente
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
    networks:
      - rinha-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: "0.2" # <-- CPU um pouco reduzida
          # ✅ MEMÓRIA REDUZIDA
          memory: "50M"

  api01: &api-template
    build: .
    hostname: api01
    environment:
      - MONGODB_URI=mongodb://mongo:27017/rinhaDB?replicaSet=rs0
      - REDIS_HOST=redis
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-1
    ports:
      - "8081:8080"
    restart: always
    networks:
      - rinha-network
      - payment-processor
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.3" # <-- CPU ajustada
          # A memória de 55M para GraalVM é ótima.
          memory: "55M"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-buffer-size: "4m" # Buffer de 4MB em memória

  api02:
    <<: *api-template
    hostname: api02
    ports:
      - "8082:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/rinhaDB?replicaSet=rs0
      - REDIS_HOST=redis
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-2

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api01:
        condition: service_healthy
      api02:
        condition: service_healthy
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.2" # <-- CPU ajustada
          # ✅ Limite explícito para o Nginx
          memory: "25M"

volumes:
  mongo_data:

networks:
  rinha-network:
    driver: bridge
  # Adicione esta linha para conectar com os processadores:
  payment-processor:
    external: true
    name: payment-processor