version: '3.8'

services:
  mongo:
    image: mongo:7.0
    hostname: mongo
    restart: unless-stopped
    command: >
      mongod --replSet rs0 --bind_ip_all --wiredTigerCacheSizeGB 0.25
    volumes:
      - mongo_data:/data/db
    networks:
      - rinha-network
    healthcheck:
      test: |
        mongosh --host mongo:27017 --quiet --eval "
          try {
            const status = rs.status();
            if (status.myState === 1 || status.myState === 2) quit(0);
            else quit(1);
          } catch (e) {
            rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'mongo:27017' }] });
            quit(1);
          }"
      interval: 8s
      timeout: 5s
      retries: 15
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.6" # ✅ 0.6 CPU para o Mongo
          memory: "260M" # ✅ 260MB para o Mongo

  mongo-setup:
    image: mongo:7.0
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./setup-mongo.sh:/setup-mongo.sh:ro
    networks:
      - rinha-network
    environment:
      - MONGO_HOST=mongo
    entrypoint: ["bash", "/setup-mongo.sh"]
    restart: "no"

  api01:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    depends_on:
      mongo-setup:
        condition: service_completed_successfully
    environment:
      - MONGODB_URI=mongodb://mongo:27017/rinhaDB?replicaSet=rs0&retryWrites=true&w=majority
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-1
      - APP_RUN_MODE=api # ✅ Roda somente como API
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.35" # ✅ Balanceado para API
          memory: "110M" # ✅ Balanceado para API
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 45s

  api02:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api02
    depends_on:
      mongo-setup:
        condition: service_completed_successfully
    environment:
      - MONGODB_URI=mongodb://mongo:27017/rinhaDB?replicaSet=rs0&retryWrites=true&w=majority
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-2
      - APP_RUN_MODE=api # ✅ Roda somente como API
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.35" # ✅ Balanceado para API
          memory: "110M" # ✅ Balanceado para API
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 45s

  worker01: # ✅ Worker dedicado
    build:
      context: .
      dockerfile: Dockerfile
    hostname: worker01
    depends_on:
      mongo-setup:
        condition: service_completed_successfully
    environment:
      - MONGODB_URI=mongodb://mongo:27017/rinhaDB?replicaSet=rs0&retryWrites=true&w=majority
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=WORKER-1
      - APP_RUN_MODE=worker # ✅ Roda somente como Worker
      - SPRING_PROFILES_ACTIVE=worker # ✅ Ativa o perfil que desliga a web
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6" # ✅ Mais CPU para o trabalho pesado
          memory: "120M" # ✅ Mais memória para o processamento em lote

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api01:
        condition: service_healthy
      api02:
        condition: service_healthy
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.1" # ✅ CPU mínima para o Nginx
          memory: "20M" # ✅ Memória mínima para o Nginx

volumes:
  mongo_data:

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true
    name: payment-processor