version: '3.8'

services:
  api01:
    environment:
      - SPRING_PROFILES_ACTIVE=k6
      - APP_RUN_MODE=api
      - LOG_LEVEL_APP=WARN
      - LOG_LEVEL_ROOT=WARN

  api02:
    environment:
      - SPRING_PROFILES_ACTIVE=k6
      - APP_RUN_MODE=hybrid
      - LOG_LEVEL_APP=WARN
      - LOG_LEVEL_ROOT=WARN
      - APP_OUTBOX_BATCH_SIZE=20
      - APP_OUTBOX_MAX_CONCURRENCY=4
      - APP_OUTBOX_PROCESSING_DELAY_MS=80
