version: "3.5"

services:
  api01: # Primeira instância da API
    image: leoarabe/rinha-backend-2025-kotlin
    hostname: api01
    restart: always
    networks:
      - rinha
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 100MB

  api02: # Segunda instância da API
    image: leoarabe/rinha-backend-2025-kotlin
    hostname: api02
    restart: always
    networks:
      - rinha
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 100MB

  mongo: # MongoDB como banco de dados
    image: mongo:6.0
    hostname: mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 100MB

  nginx: # Load Balancer que expõe a porta 9999
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 100MB

networks:
  rinha:
    external: true
