services:
  api01:
    image: leoarabe/rinha-backend-2025-kotlin
    hostname: api01
    restart: always
    networks:
      - rinha
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/rinhaDB
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150M"

  api02:
    image: leoarabe/rinha-backend-2025-kotlin
    hostname: api02
    restart: always
    networks:
      - rinha
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/rinhaDB
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150M"

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    hostname: mongo
    volumes:
      - ./data:/data/db
    networks:
      - rinha
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand('ping').ok" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "200M"


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50M"

networks:
  rinha:
    driver: bridge
