version: '3.8'

services:
  mongo:
    image: mongo:7.0
    hostname: mongo
    restart: unless-stopped
    command: >
      mongod --replSet rs0 --bind_ip_all --wiredTigerCacheSizeGB 0.25
    volumes:
      - mongo_data:/data/db
    networks:
      - rinha-network
    healthcheck:
      test: |
        mongosh --host mongo:27017 --quiet --eval "
          try {
            const s = rs.status();
            if (s.myState === 1 || s.myState === 2) quit(0); else quit(1);
          } catch (e) {
            rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'mongo:27017' }] });
            quit(1);
          }"
      interval: 8s
      timeout: 5s
      retries: 15
      start_period: 27s
    deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: "260M"

  mongo-setup:
    image: mongo:7.0
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./setup-mongo.sh:/setup-mongo.sh:ro
    environment:
      - MONGO_HOST=mongo
    networks:
      - rinha-network
    entrypoint: ["bash", "/setup-mongo.sh"]
    restart: "no"

  api01:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    depends_on:
      mongo-setup:
        condition: service_completed_successfully
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - APP_RUN_MODE=api
      - INSTANCE_ID=API-1
      - SERVER_PORT=8080
      - MONGODB_URI=mongodb://mongo:27017/rinhaDB?replicaSet=rs0&w=majority
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - LOG_LEVEL_APP=WARN
      - LOG_LEVEL_ROOT=WARN
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "32M"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 40s

  api02:
    build:
      context: .
    hostname: api02
    depends_on:
      mongo-setup:
        condition: service_completed_successfully
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - APP_RUN_MODE=hybrid    # ✅ API + worker
      - INSTANCE_ID=API-2
      - SERVER_PORT=8080
      - MONGODB_URI=mongodb://mongo:27017/rinhaDB?replicaSet=rs0&w=majority
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - APP_OUTBOX_BATCH_SIZE=10
      - APP_OUTBOX_MAX_CONCURRENCY=2
      - APP_OUTBOX_PROCESSING_DELAY_MS=120
      - LOG_LEVEL_APP=WARN
      - LOG_LEVEL_ROOT=WARN
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "43M"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    depends_on:
      api01:
        condition: service_healthy
      api02:
        condition: service_healthy
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15M"

volumes:
  mongo_data:

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true
    name: payment-processor
