# ===================================================================
# Default Application Configuration
# ===================================================================
server:
  port: ${SERVER_PORT:8080}
  netty:
    connection-timeout: 2s
    h2c-max-content-length: 0B

app:
  instance-id: ${INSTANCE_ID:API-LOCAL}
  run-mode: ${APP_RUN_MODE:api}   # api | worker | hybrid
  fail-on-persist-error: ${APP_FAIL_ON_PERSIST_ERROR:false}

  outbox:
    processing-delay-ms: ${APP_OUTBOX_PROCESSING_DELAY_MS:120}  # tick curto, mas controlado
    batch-size: ${APP_OUTBOX_BATCH_SIZE:10}                     # lote pequeno
    max-concurrency: ${APP_OUTBOX_MAX_CONCURRENCY:2}            # concorrência baixa no hybrid
    lock-timeout-minutes: ${APP_OUTBOX_LOCK_TIMEOUT_MINUTES:3}

  health-check:
    delay-ms: ${APP_HEALTH_CHECK_DELAY_MS:5000}
    leader-ttl-seconds: ${APP_HEALTH_LEADER_TTL_SECONDS:10}

  processor:
    default:
      url: ${PROCESSOR_DEFAULT_URL:http://payment-processor-default:8080}
    fallback:
      url: ${PROCESSOR_FALLBACK_URL:http://payment-processor-fallback:8080}

  http:
    connect-timeout-ms: ${APP_HTTP_CONNECT_TIMEOUT_MS:2000}
    max-in-memory-bytes: ${APP_HTTP_MAX_IN_MEMORY_BYTES:262144} # 256 KB

  summary:
    timeout-seconds: ${APP_SUMMARY_TIMEOUT_SECONDS:6}

spring:
  application:
    name: rinha-backend-2025
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongo:27017/rinhaDB?replicaSet=rs0&w=majority}
      pool:
        min-size: ${SPRING_DATA_MONGODB_POOL_MIN_SIZE:1}
        max-size: ${SPRING_DATA_MONGODB_POOL_MAX_SIZE:12}
        max-wait-time-ms: ${SPRING_DATA_MONGODB_POOL_MAX_WAIT_TIME_MS:2000}
        max-idle-time: ${SPRING_DATA_MONGODB_POOL_MAX_IDLE_TIME_MS:45000}
  jackson:
    default-property-inclusion: non_null
  webflux:
    multipart:
      max-in-memory-size: ${SPRING_WEBFLUX_MULTIPART_MAX_IN_MEMORY_BYTES:0}  # desliga buffer de upload

payment:
  retry:
    max-attempts: ${PAYMENT_RETRY_MAX_ATTEMPTS:2}
    max-backoff-seconds: ${PAYMENT_RETRY_MAX_BACKOFF_SECONDS:25}
  circuit-breaker:
    request-timeout-seconds: ${PAYMENT_REQUEST_TIMEOUT_SECONDS:4}
    failure-threshold: ${PAYMENT_CIRCUIT_BREAKER_FAILURE_THRESHOLD:5}
    recovery-timeout-seconds: ${PAYMENT_CIRCUIT_BREAKER_RECOVERY_SECONDS:20}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:WARN}
    org.springframework: ${LOG_LEVEL_SPRING:WARN}
    org.mongodb.driver: ${LOG_LEVEL_MONGO:ERROR}
    reactor.netty: ${LOG_LEVEL_REACTOR_NETTY:ERROR}
    com.estagiario.gobots.rinha_backend: ${LOG_LEVEL_APP:INFO}
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger - %msg%n"

# ===================================================================
# Profiles
# ===================================================================
---
spring:
  config:
    activate:
      on-profile: "k6"

app:
  outbox:
    batch-size: 15
    max-concurrency: 3
    processing-delay-ms: 80
    lock-timeout-minutes: 2

payment:
  retry:
    max-attempts: 2
    max-backoff-seconds: 20

---
spring:
  config:
    activate:
      on-profile: "no-web"
  main:
    web-application-type: none
